version: "3"
name: test_ai
networks:
  loki:
services:
    kaldi-en:
        ports:
            - 2700:2700
        image: alphacep/kaldi-en:latest
        networks:
          - loki
    loki:
        image: grafana/loki:2.9.0
        ports:
          - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        networks:
          - loki
    promtail:
        image: grafana/promtail:2.9.0
        volumes:
          - ./logs:/var/log
        command: -config.file=/etc/promtail/config.yml
        networks:
          - loki
    grafana:
        environment:
          - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        entrypoint:
          - sh
          - -euc
          - |
            mkdir -p /etc/grafana/provisioning/datasources
            cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              access: proxy
              orgId: 1
              url: http://loki:3100
              basicAuth: false
              isDefault: true
              version: 1
              editable: false
            EOF
            /run.sh
        image: grafana/grafana:latest
        volumes:
          - './GrafanaData:/var/lib/grafana'
        ports:
          - "3000:3000"
        networks:
          - loki